# Set up and run this Streamlit App
import streamlit as st
from helper_functions import llm # <--- This is the helper function that we have created 🆕
from logics import customer_query_handler
from auth import check_password

def process_user_message(user_input):
    delimiter = "```"

    # Process 1: If Courses are found, look them up
    category_n_course_name = customer_query_handler.identify_category_and_courses(user_input)
    print("category_n_course_name : ", category_n_course_name)

    # Process 2: Get the Course Details
    course_details = customer_query_handler.get_course_details(category_n_course_name)

    # Process 3: Generate Response based on Course Details
    reply = customer_query_handler.generate_response_based_on_course_details(user_input, course_details)

    return reply

# region <--------- Streamlit App Configuration --------->
st.set_page_config(
    layout="centered",
    page_title="My Streamlit App"
)
# endregion <--------- Streamlit App Configuration --------->
if not check_password():
    st.stop()

st.title("Streamlit App Demo")

form = st.form(key="form")
form.subheader("Prompt")

user_prompt = form.text_area("Enter your prompt here", height=200)

if form.form_submit_button("Submit"):
    st.toast(f"User Input Submitted - {user_prompt}")
    # response = llm.get_completion(user_prompt) # <--- This calls the helper function that we have created 🆕
    response = process_user_message(user_prompt)
    st.write(response) # <--- This displays the response generated by the LLM onto the frontend 🆕
    print(f"User Input is {user_prompt}")

